export const cuisineOptions = [
  "African",
  "American",
  "Argentinian",
  "Asian",
  "Bakery",
  "Bangladeshi",
  "Bar / Pub Food",
  "BBQ",
  "Brazilian",
  "Breakfast & Brunch",
  "Bubble Tea",
  "Burgers",
  "Burmese",
  "Burrito",
  "Cajun / Creole",
  "Caribbean",
  "Chilean",
  "Chinese",
  "Taiwanese",
  "Coffee and Tea",
  "Colombian",
  "Dessert",
  "Ecuadorian",
  "Egyptian",
  "Empanada",
  "European",
  "Filipino",
  "Fish & Seafood",
  "French",
  "Georgian",
  "German",
  "Greek",
  "Guetemalan",
  "Halal",
  "Hawaiian",
  "Ice Crean & Frozen Yogurt",
  "Indian",
  "Indonesian",
  "Israeli",
  "Italian",
  "Japanese",
  "Korean",
  "Latin American",
  "Lebanese",
  "Malaysian",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Modern Australian",
  "Moroccan",
  "Pakistani",
  "Peruvian",
  "Pizza",
  "Poke",
  "Portuguese",
  "Russian",
  "Seafood",
  "Southern",
  "Spanish",
  "Sushi",
  "Steakhouse",
  "Tacos",
  "Thai",
  "Turkish",
  "Vegetarian / Vegan",
  "Venezuelan",
  "Vietnamese",
  "Other",
];
