"""Created restaurant model

Revision ID: 6fe2718438e9
Revises: 5341103d3fc6
Create Date: 2023-08-26 10:58:58.444214

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '6fe2718438e9'
down_revision = '5341103d3fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('address', sa.String(
                        length=100), nullable=False),
                    sa.Column('city', sa.String(length=100), nullable=False),
                    sa.Column('state', sa.String(length=50), nullable=False),
                    sa.Column('country', sa.String(
                        length=100), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('cuisine', sa.String(
                        length=100), nullable=False),
                    sa.Column('dietary', sa.String(length=100), nullable=True),
                    sa.Column('price_range', sa.String(
                        length=10), nullable=False),
                    sa.Column('opens_at', sa.String(
                        length=25), nullable=False),
                    sa.Column('closes_at', sa.String(
                        length=25), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE restaurants SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants')
    # ### end Alembic commands ###
