"""Created menu_item model

Revision ID: 9c88697f9311
Revises: 6fe2718438e9
Create Date: 2023-08-26 11:12:45.673045

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '9c88697f9311'
down_revision = '6fe2718438e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('category', sa.String(
                        length=50), nullable=False),
                    sa.Column('dietary', sa.String(length=50), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE menu_items SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    # ### end Alembic commands ###
